import type { Address, Branch, BranchId, ChainConfig, CollateralSymbol, ProtocolContracts } from '$lib/types';
import {
	PUBLIC_CHAIN_ID,
	PUBLIC_CHAIN_NAME,
	PUBLIC_CHAIN_RPC_URL,
	PUBLIC_CHAIN_BLOCK_EXPLORER,
	PUBLIC_CHAIN_CURRENCY,
	PUBLIC_WALLET_CONNECT_PROJECT_ID,
	PUBLIC_KNOWN_DELEGATES_URL,
	PUBLIC_CONTRACT_BOLD_TOKEN,
	PUBLIC_CONTRACT_COLLATERAL_REGISTRY,
	PUBLIC_CONTRACT_EXCHANGE_HELPERS_V2,
	PUBLIC_CONTRACT_GOVERNANCE,
	PUBLIC_CONTRACT_HINT_HELPERS,
	PUBLIC_CONTRACT_LQTY_STAKING,
	PUBLIC_CONTRACT_LQTY_TOKEN,
	PUBLIC_CONTRACT_MULTI_TROVE_GETTER,
	PUBLIC_CONTRACT_REDEMPTION_HELPER,
	PUBLIC_CONTRACT_WETH,
	PUBLIC_COLL_0_TOKEN_ID,
	PUBLIC_COLL_1_TOKEN_ID,
	PUBLIC_COLL_2_TOKEN_ID,
	PUBLIC_COLL_0_CONTRACT_ACTIVE_POOL,
	PUBLIC_COLL_0_CONTRACT_BORROWER_OPERATIONS,
	PUBLIC_COLL_0_CONTRACT_COLL_SURPLUS_POOL,
	PUBLIC_COLL_0_CONTRACT_COLL_TOKEN,
	PUBLIC_COLL_0_CONTRACT_DEFAULT_POOL,
	PUBLIC_COLL_0_CONTRACT_LEVERAGE_ZAPPER,
	PUBLIC_COLL_0_CONTRACT_PRICE_FEED,
	PUBLIC_COLL_0_CONTRACT_SORTED_TROVES,
	PUBLIC_COLL_0_CONTRACT_STABILITY_POOL,
	PUBLIC_COLL_0_CONTRACT_TROVE_MANAGER,
	PUBLIC_COLL_0_CONTRACT_TROVE_NFT,
	PUBLIC_COLL_1_CONTRACT_ACTIVE_POOL,
	PUBLIC_COLL_1_CONTRACT_BORROWER_OPERATIONS,
	PUBLIC_COLL_1_CONTRACT_COLL_SURPLUS_POOL,
	PUBLIC_COLL_1_CONTRACT_COLL_TOKEN,
	PUBLIC_COLL_1_CONTRACT_DEFAULT_POOL,
	PUBLIC_COLL_1_CONTRACT_LEVERAGE_ZAPPER,
	PUBLIC_COLL_1_CONTRACT_PRICE_FEED,
	PUBLIC_COLL_1_CONTRACT_SORTED_TROVES,
	PUBLIC_COLL_1_CONTRACT_STABILITY_POOL,
	PUBLIC_COLL_1_CONTRACT_TROVE_MANAGER,
	PUBLIC_COLL_1_CONTRACT_TROVE_NFT,
	PUBLIC_COLL_2_CONTRACT_ACTIVE_POOL,
	PUBLIC_COLL_2_CONTRACT_BORROWER_OPERATIONS,
	PUBLIC_COLL_2_CONTRACT_COLL_SURPLUS_POOL,
	PUBLIC_COLL_2_CONTRACT_COLL_TOKEN,
	PUBLIC_COLL_2_CONTRACT_DEFAULT_POOL,
	PUBLIC_COLL_2_CONTRACT_LEVERAGE_ZAPPER,
	PUBLIC_COLL_2_CONTRACT_PRICE_FEED,
	PUBLIC_COLL_2_CONTRACT_SORTED_TROVES,
	PUBLIC_COLL_2_CONTRACT_STABILITY_POOL,
	PUBLIC_COLL_2_CONTRACT_TROVE_MANAGER,
	PUBLIC_COLL_2_CONTRACT_TROVE_NFT
} from '$env/static/public';

// Chain configuration
export const CHAIN_CONFIG: ChainConfig = {
	id: parseInt(PUBLIC_CHAIN_ID || '1', 10),
	name: PUBLIC_CHAIN_NAME || 'Ethereum',
	rpcUrl: PUBLIC_CHAIN_RPC_URL || 'https://cloudflare-eth.com',
	blockExplorer: parseBlockExplorer(PUBLIC_CHAIN_BLOCK_EXPLORER || ''),
	currency: parseCurrency(PUBLIC_CHAIN_CURRENCY || 'Ether|ETH|18')
};

export const WALLET_CONNECT_PROJECT_ID = PUBLIC_WALLET_CONNECT_PROJECT_ID || '';
export const KNOWN_DELEGATES_URL = PUBLIC_KNOWN_DELEGATES_URL || '';

// Protocol-level contracts
export const PROTOCOL_CONTRACTS: ProtocolContracts = {
	BOLD_TOKEN: PUBLIC_CONTRACT_BOLD_TOKEN as Address,
	COLLATERAL_REGISTRY: PUBLIC_CONTRACT_COLLATERAL_REGISTRY as Address,
	EXCHANGE_HELPERS_V2: PUBLIC_CONTRACT_EXCHANGE_HELPERS_V2 as Address,
	GOVERNANCE: PUBLIC_CONTRACT_GOVERNANCE as Address,
	HINT_HELPERS: PUBLIC_CONTRACT_HINT_HELPERS as Address,
	LQTY_STAKING: PUBLIC_CONTRACT_LQTY_STAKING as Address,
	LQTY_TOKEN: PUBLIC_CONTRACT_LQTY_TOKEN as Address,
	MULTI_TROVE_GETTER: PUBLIC_CONTRACT_MULTI_TROVE_GETTER as Address,
	REDEMPTION_HELPER: PUBLIC_CONTRACT_REDEMPTION_HELPER as Address,
	WETH: PUBLIC_CONTRACT_WETH as Address
};

// Collateral token IDs
const COLL_TOKEN_IDS: Record<number, CollateralSymbol> = {
	0: (PUBLIC_COLL_0_TOKEN_ID || 'ETH') as CollateralSymbol,
	1: (PUBLIC_COLL_1_TOKEN_ID || 'WSTETH') as CollateralSymbol,
	2: (PUBLIC_COLL_2_TOKEN_ID || 'RETH') as CollateralSymbol
};

// Branch contracts (3 collateral types: ETH, WSTETH, RETH)
export const BRANCHES: Branch[] = [
	{
		id: 0 as BranchId,
		symbol: COLL_TOKEN_IDS[0],
		name: 'Wrapped ETH',
		contracts: {
			ACTIVE_POOL: PUBLIC_COLL_0_CONTRACT_ACTIVE_POOL as Address,
			BORROWER_OPERATIONS: PUBLIC_COLL_0_CONTRACT_BORROWER_OPERATIONS as Address,
			COLL_SURPLUS_POOL: PUBLIC_COLL_0_CONTRACT_COLL_SURPLUS_POOL as Address,
			COLL_TOKEN: PUBLIC_COLL_0_CONTRACT_COLL_TOKEN as Address,
			DEFAULT_POOL: PUBLIC_COLL_0_CONTRACT_DEFAULT_POOL as Address,
			LEVERAGE_ZAPPER: PUBLIC_COLL_0_CONTRACT_LEVERAGE_ZAPPER as Address,
			PRICE_FEED: PUBLIC_COLL_0_CONTRACT_PRICE_FEED as Address,
			SORTED_TROVES: PUBLIC_COLL_0_CONTRACT_SORTED_TROVES as Address,
			STABILITY_POOL: PUBLIC_COLL_0_CONTRACT_STABILITY_POOL as Address,
			TROVE_MANAGER: PUBLIC_COLL_0_CONTRACT_TROVE_MANAGER as Address,
			TROVE_NFT: PUBLIC_COLL_0_CONTRACT_TROVE_NFT as Address
		}
	},
	{
		id: 1 as BranchId,
		symbol: COLL_TOKEN_IDS[1],
		name: 'Wrapped stETH',
		contracts: {
			ACTIVE_POOL: PUBLIC_COLL_1_CONTRACT_ACTIVE_POOL as Address,
			BORROWER_OPERATIONS: PUBLIC_COLL_1_CONTRACT_BORROWER_OPERATIONS as Address,
			COLL_SURPLUS_POOL: PUBLIC_COLL_1_CONTRACT_COLL_SURPLUS_POOL as Address,
			COLL_TOKEN: PUBLIC_COLL_1_CONTRACT_COLL_TOKEN as Address,
			DEFAULT_POOL: PUBLIC_COLL_1_CONTRACT_DEFAULT_POOL as Address,
			LEVERAGE_ZAPPER: PUBLIC_COLL_1_CONTRACT_LEVERAGE_ZAPPER as Address,
			PRICE_FEED: PUBLIC_COLL_1_CONTRACT_PRICE_FEED as Address,
			SORTED_TROVES: PUBLIC_COLL_1_CONTRACT_SORTED_TROVES as Address,
			STABILITY_POOL: PUBLIC_COLL_1_CONTRACT_STABILITY_POOL as Address,
			TROVE_MANAGER: PUBLIC_COLL_1_CONTRACT_TROVE_MANAGER as Address,
			TROVE_NFT: PUBLIC_COLL_1_CONTRACT_TROVE_NFT as Address
		}
	},
	{
		id: 2 as BranchId,
		symbol: COLL_TOKEN_IDS[2],
		name: 'Rocket Pool ETH',
		contracts: {
			ACTIVE_POOL: PUBLIC_COLL_2_CONTRACT_ACTIVE_POOL as Address,
			BORROWER_OPERATIONS: PUBLIC_COLL_2_CONTRACT_BORROWER_OPERATIONS as Address,
			COLL_SURPLUS_POOL: PUBLIC_COLL_2_CONTRACT_COLL_SURPLUS_POOL as Address,
			COLL_TOKEN: PUBLIC_COLL_2_CONTRACT_COLL_TOKEN as Address,
			DEFAULT_POOL: PUBLIC_COLL_2_CONTRACT_DEFAULT_POOL as Address,
			LEVERAGE_ZAPPER: PUBLIC_COLL_2_CONTRACT_LEVERAGE_ZAPPER as Address,
			PRICE_FEED: PUBLIC_COLL_2_CONTRACT_PRICE_FEED as Address,
			SORTED_TROVES: PUBLIC_COLL_2_CONTRACT_SORTED_TROVES as Address,
			STABILITY_POOL: PUBLIC_COLL_2_CONTRACT_STABILITY_POOL as Address,
			TROVE_MANAGER: PUBLIC_COLL_2_CONTRACT_TROVE_MANAGER as Address,
			TROVE_NFT: PUBLIC_COLL_2_CONTRACT_TROVE_NFT as Address
		}
	}
];

// Helper to get branch by ID or symbol
export function getBranch(idOrSymbol: BranchId | CollateralSymbol): Branch {
	const branch =
		typeof idOrSymbol === 'number'
			? BRANCHES[idOrSymbol]
			: BRANCHES.find((b) => b.symbol === idOrSymbol);

	if (!branch) {
		throw new Error(`Invalid branch: ${idOrSymbol}`);
	}
	return branch;
}

// Parse block explorer string: "Name|URL"
function parseBlockExplorer(value: string): { name: string; url: string } | undefined {
	if (!value) return undefined;
	const [name, url] = value.split('|');
	return name && url ? { name, url } : undefined;
}

// Parse currency string: "Name|Symbol|Decimals"
function parseCurrency(value: string): { name: string; symbol: string; decimals: number } {
	const [name, symbol, decimals] = value.split('|');
	return {
		name: name ?? 'Ether',
		symbol: symbol ?? 'ETH',
		decimals: parseInt(decimals ?? '18', 10)
	};
}
